### ISSUE TITLE
Test server mysteriously was down

### ISSUE THREAD

**Issue by Newman101** [18F/openopps-platform#1131]
Hi all. 

FYI: Community test server on https://openopps-test.18f.gov/ seems to be broken.

Error message: "Internal Server Error". (Anything from HTTP status code 500 to 599?)

Please investigate. 

Thank you.

**Comment by ultrasaurus** [comment]
@Newman101 works for me -- is it still failing for you?   can anyone else report success or failure?

**Comment by Newman101** [comment]
Looks like it's back up now. You might want to check the server error logs what caused the problem.

**Comment by ultrasaurus** [comment]
@Newman101 will do!  Let's leave this issue open for that.

**Comment by Newman101** [comment]
A good idea, I had a initial suspicion that it might have something to do with those bad gateway requests in earlier tickets (because 502 status basically means that the server received an invalid response from the upstream server it accessed in attempting to fulfill the request) so that might be a good place to start looking. But I do believe the logs tell a bit more in detail.

**Comment by ultrasaurus** [comment]
sadly we didn't actually have log history at the time of the event, but we do now!  Let's open another issue if this happens again
