### ISSUE TITLE
Save as Draft

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1143]
People used to just post opportunities and they would go to Lisa for review. There was a lot of feedback that that didn't work for people. Repeat task creators would keep separate spreadsheets of their tasks in draft, which gave Lisa ZERO visibility and slowed down the process. We've gotten users to change their behavior and start drafting in the platform. 

Admins would expect to be able to see a list of drafts (that people are working on), separate from those that are in review.

Task creator view:
- User selects "Save draft"
- User stays on editing page.
- User receives notice stating that the draft has been saved.
- Edit page includes "Save draft" and "Submit for review" button.
- Edit Opportunity State
  -  needs to include "Submited" 
- Notification:
  - changing state to "Submited" should trigger current notification
  - saving as draft for the first time, generates a one time email with a link to the draft -- based on the creation date and the updated date matching  (people really use the email notifications to find direct links to their tasks and as reminders about next steps)

Admin view:
- Current "Draft" is renamed to "Submitted" 
- New *actual* "Draft" tab is in the far right

**Comment by ultrasaurus** [comment]
-> @vz3 to add details about UX for this feature

**Comment by vz3** [comment]
Task creator view:
- User selects "Save draft"
- User stays on editing page.
- User receives notice stating that the draft has been saved.
- Edit page includes "Save draft" and "Submit for review" button.

Admin view:
- Current "Draft" is renamed to "Submitted for review" or something similar
- New *actual* "Draft" tab is created, but is not default view for admin (Probably becomes last tab)

**Comment by ultrasaurus** [comment]
Also...

* Edit Opportunity State: needs to include "Submitted for Review" (or "In Review" but should be consistent with admin view)
* changing state to "Submitted for review" should trigger current notification, saving as draft should not generate any notifications -- maybe setting something back to draft or creating a new draft should   (people really use the email notifications to find direct links to their tasks and as reminders about next steps, but would make sense to get the feature working then add notifications when we can see how it feels)

What do you think about an in-page notice (we have a standard notice bar at the top) that the draft has been saved and will be linked from your profile page?  or maybe just add to the content of the email?

**Comment by LisaLNelson** [comment]
One problem I frequently have to address with new task creators is their not knowing the process and not referring to the TC toolkit.  I am not sure which of these will make the biggest impact on their remembering where to look for the draft, but my gut tells me it needs to be in the email so they can refer back to it easily to find the info.

**Comment by rogeruiz** [comment]
I'm working on this ticket now, and I will be compiling all the ideas here and what we've discussed in standup and iteration planning within the upcoming pull request.

**Comment by rogeruiz** [comment]
For your reference, here's a link _to_ the opportunity: <NAME>

**Comment by ultrasaurus** [comment]
Notes from today's testing session

TO DO: 
- [ ] change Lisa to bcc in config
- [ ] Change Opportunity State should not be available until after the task has been submitted (hide for draft tasks)
- [ ] Add submitted to admin dashboard overview under Opportunities in top-right
- Admin > Tasks: 
  - [ ] make it so the tabs are mutually exclusive (e.g.: Open -> Open without Signups, omit assigned,   Signups -> Open with Sign Ups, omit assigned)
  - [ ] layout improvements
- [ ] on task/edit:  [Submit For Review] [Save Draft] [Discard Changes]

Rough test plan
- create a draft & save it
- carefully proof-read email
- look at admin panel & profile
- change the draft
- submit
- look at admin panel
- approve

Notes
- draft opportunities aren’t validated, you can click on the label (when it appears in a list) to open the draft
- task creator should get an email when first saving a draft, but not when saving an existing draft after editing
- Opportunity state appears under the headline in the task view page

**Comment by ultrasaurus** [comment]
Also, agreed to defer as future improvement:  create a drafts section on the profile page -- when this is complete, would be good to write that up as an open issue with "Help Wanted" tag

**Comment by ultrasaurus** [comment]
small change needed - if an opportunity is not in draft state, let's have just a save button so people can make small edits without changing the opportunity state

**Comment by ultrasaurus** [comment]
This is complete and deployed to production!  thanks @rogeruiz :tada:
