### ISSUE TITLE
seems like profile updates are failing in IE11, but Firefox and Chrome are ok

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1180]
"I was able to upload a picture but every time I edit the Bio or add interests/skills and click save it wont save the Bio and other profile changes I’ve made."  (in IE11)

same person could update later in Firefox
also @LisaLNelson verified that profile editing fails for her in IE, yet works in Chrome

**Comment by ultrasaurus** [comment]
@rogeruiz -- did you fix this?

**Comment by rogeruiz** [comment]
Hey @ultrasaurus, This should be fixed. I was able to successfully save my profile data locally in IE11 after this commit 8243ef0b3a510dce7201664137e0e401440b4300 was pushed.

**Comment by ultrasaurus** [comment]
great!
