### ISSUE TITLE
https://groups.google.com/forum/#!forum/midascrowd link in README doesn't work

### ISSUE THREAD

**Issue by onceuponatimeforever** [18F/openopps-platform#1202]
The link specified in `README` goes to a 404 page.

**Comment by rogeruiz** [comment]
Hey @onceuponatimeforever 

We've recently been migrating the Midas name over to Open Opps. Thanks for catching this bug. We're monitoring changes such as this one within issue #907 if you'd like to follow along.

[The new URL for the Google group can be found here](https://groups.google.com/a/gsa.gov/forum/#!forum/openopps)

**Comment by ultrasaurus** [comment]
Actually the open source group is:  https://groups.google.com/forum/#!forum/openopps-platform
