### ISSUE TITLE
As a contributor, I would like to know how to label PRs that may require a Database migration.

### ISSUE THREAD

**Issue by onceuponatimeforever** [18F/openopps-platform#1203]
https://github.com/18F/openopps-platform/blob/dev/CONTRIBUTING.md#reviewing-pull-requests has an incomplete last sentence.

**Comment by rogeruiz** [comment]
Hey @onceuponatimeforever 

The Contributing documentation seems to be incomplete. Thanks for catching this. The contributing guide may need to be reviewed and tweaked along with completing that last sentence.
