### ISSUE TITLE
When I create a Full-Time Detail, I would like to see some helper text

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1230]
Updating the UI on `TaskFormCreationView` and `TaskFormEditView` to facilitate the creation of Full-Time Detail tasks with pre-populated Agency-specific template data for the description of the task 

- [x] Move the following (currently step 3) to Step 1:
![image](https://cloud.githubusercontent.com/assets/41906/12622018/491da7b8-c4d8-11e5-8222-2a470c0cef06.png)
- [x] On task creation only, when I select “Full-time Detail” then there would be some sample text added to “description”  (if I haven’t modified it)
- [x] a button: [Show Default Description] to reveal special help text (which is the default description text, but we don't want to invite confusion by adding or modifying the editable text after the creator has already started the editing process
- [x] make the sample text configurable in `assets/js/backbone/config/ui.json`  and update CONFIG.md. If configuration is not present, the  [Show Default Description] button should not appear.  It must support markdown with links and formatting that can be entered in the description area of this page.  Newlines need to work, and if any special escaping is required, it needs to be documented.
```
{
  "full-time-detail": {
    "description": "this is some text"
  }
}
```

Mockup :
![image](https://cloud.githubusercontent.com/assets/41906/13581254/dd7e5f14-e45a-11e5-8a6a-242957b77ee3.png)

Note: the Full-Time detail UI is present when you run the database script `tools/postgres/addGSAFullTimeDetail.js` and then log in with an account where your "agency" is set to "General Services Administration (GSA)"

**Comment by orangewise** [comment]
Hi @ultrasaurus, this is a redesign of the create task page:

<img width="663" alt="create" src="https://cloud.githubusercontent.com/assets/244419/13788908/1730406e-eae2-11e5-94f1-17996a0a2696.png">

You can also see the location of the 'Show default description link'.

**Comment by orangewise** [comment]
<img width="698" alt="edit" src="https://cloud.githubusercontent.com/assets/244419/13788979/64e6ea9c-eae2-11e5-800a-449005c98c16.png">

And this is the redesigned 'edit task' page. All the elements of the 'Who, When, and Where are moved up. It also contains the 'Show Default Description' link.

**Comment by ultrasaurus** [comment]
@orangewise I like the approach of using a link instead of a button, then the description could open right below it, which I think makes sense … and then prolly change link text to “Hide Default Description"

**Comment by orangewise** [comment]
@ultrasaurus, nice, will do that.

**Comment by ultrasaurus** [comment]
locally testing worked fine for me -- I've now merged to the `dev` branch, but we won't be able to see the feature on the test server yet since it's not configured for full-time details.  I'll set that up today so we can do a bit more interactive testing.

**Comment by ultrasaurus** [comment]
Reviewed with OHRM today, all good!  Additional work captured as separate issues:
* need to update text: https://github.com/18F/openopps-platform/issues/1274 
* usability testing https://github.com/18F/openopps-platform/issues/1279
