### ISSUE TITLE
when a new Opportunity is submitted, the email message should clarify next steps

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1239]
Right now the email doesn't let people know that there is an approval step:

![image](https://cloud.githubusercontent.com/assets/41906/12948244/a4fff24c-cfb5-11e5-85b2-5e77bae926fd.png)

(The system can be configured not to have new opportunity moderation, but we should have the text match the default configuration.)

**Comment by ultrasaurus** [comment]
@LisaLNelson can you propose some text that let's people know that their Opportunity will be reviewed and they will get another email when it is posted...

**Comment by LisaLNelson** [comment]
You will be notified when your task has been approved and when people sign up.
