### ISSUE TITLE
help links on Opportunity Edit page aren't click-able

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1240]
https://openopps-test.18f.gov/tasks/64/edit  

The links appear in blue, but aren't actually clickable
![image](https://cloud.githubusercontent.com/assets/41906/12948464/38ed039a-cfb7-11e5-9337-8730fd9e3028.png)

**Comment by ultrasaurus** [comment]
@LisaLNelson it appears they were never hooked up to anything!  Can you provide the URLs where these should go.  Should be an easy fix!

**Comment by LisaLNelson** [comment]
Toolkit: http://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/

Tips: http://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/10-tips-for-creating-the-perfect-open-opportunity-task/
