### ISSUE TITLE
full-time details on the staging server

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1251]
When logged in as a GSA employee -- with my profile agency set to "General Services Administration (GSA)" I should see a Full Time Detail option on the [create opportunity page](https://openopps-staging.18f.gov/tasks/new)

**Comment by ultrasaurus** [comment]
I updated the staging server so it has the full-time detail for GSA configured in the database

**Comment by ultrasaurus** [comment]
also available now on the open source test server: https://openopps-test.18f.gov

**Comment by LisaLNelson** [comment]
Reviewed with OHRM today.

**Comment by LisaLNelson** [comment]
Reviewed with OHRM today.
