### ISSUE TITLE
As a task taker I need to be able to update my profile if I change agencies.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/openopps-platform#1253]
Right now when someone changes agencies they must:

- notify the admin of the change

- the admin must go into the account and update the email address

- Admin creates a temporary password and contacts the person telling them they can go into their account and the temp password.

**Comment by ultrasaurus** [comment]
why can't they just edit their profile and change it?

**Comment by LisaLNelson** [comment]
Because their email account has been closed at the old agency and they usually don't have a new address before the old one closes.

**Comment by ultrasaurus** [comment]
if they haven't forgotten their password, they can still log in.  If they forgot their password and don't have access to their old email, I can't think of a solution besides a human admin helping them...

**Comment by LisaLNelson** [comment]
OK

**Comment by ultrasaurus** [comment]
closing for now, feel free to re-open if you have an idea of how we could help this with software!
