### ISSUE TITLE
As a task creator and a task taker I want to be able to see photos of individuals on the platfor

### ISSUE THREAD

**Issue by LisaLNelson** [18F/openopps-platform#1255]
Right now when I click on a task this is what I see, note the URL does not have a number as it should.
![screen shot 2016-03-09 at 9 11 27 pm](https://cloud.githubusercontent.com/assets/9039852/13657251/d0957264-e63b-11e5-9400-92e12f0c948c.png)

When I click on the dashboards page I do not see any of the people who completed the task only their names.  There aren't even any icon spaces where pictures go. This is what I see.
![screen shot 2016-03-09 at 9 20 12 pm](https://cloud.githubusercontent.com/assets/9039852/13657415/22c8ed3a-e63d-11e5-9820-4a5a7ae9d90d.png)

Approximately 5 minutes after I pulled the age up this appeared;
![screen shot 2016-03-09 at 9 25 36 pm](https://cloud.githubusercontent.com/assets/9039852/13657518/d5b4bb86-e63d-11e5-887f-740f1dd01399.png)

Finally when I click on the Opportunities pages I do not see the TC photo on the tasks.  
![screen shot 2016-03-09 at 9 16 49 pm](https://cloud.githubusercontent.com/assets/9039852/13657521/dc4e1c30-e63d-11e5-9ccd-ccf760c88e81.png)

**Comment by ultrasaurus** [comment]
these are two separate issues... the page at /admin/user should look like this:

![image](https://cloud.githubusercontent.com/assets/41906/13676289/0e241f28-e69a-11e5-884a-fc22ba531502.png)

Could you please edit the description above, so it includes steps to reproduce.  Logout of the web site, then start with logging in, something like:

1. Log in
2. Click on my image in the top-right, choose "Profile"
Expected: to see my profile
Actual: ....

**Comment by ultrasaurus** [comment]
fixed now
