### ISSUE TITLE
As a user of the Open Opportunities platform I would like to see the latest achievements on the dashboard.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/openopps-platform#1278]
Right now the latest achievements are not showing up on the dashboard.
![screen shot 2016-03-29 at 12 32 43 pm](https://cloud.githubusercontent.com/assets/9039852/14115766/61ed0bd2-f5aa-11e5-857c-9bbda8156655.png)

**Comment by ultrasaurus** [comment]
may be related to: https://github.com/18F/openopps-platform/issues/1158 -- probably a different issue, but may be similar failing to render when there is some kind of error
