### ISSUE TITLE
Opportunity title overlaps tags on project show page on mobile

### ISSUE THREAD

**Issue by Chessen** [18F/openopps-platform#169]
On a mobile device on the project show page, the op title will bleed over the tags for the preceeding op. 

![photo](https://cloud.githubusercontent.com/assets/4838006/3033083/e59624d0-e05f-11e3-8d9f-6fcc7cc6d9d0.PNG)

**Comment by awhig** [comment]
I think this can be closed. The layout is completely different than when this was filed. I don't see any overlapping.
<img width="314" alt="screen shot 2015-11-13 at 11 41 50 am" src="https://cloud.githubusercontent.com/assets/6233406/11155645/98a73f14-89fb-11e5-9bd4-dfe07eb605d2.png">

**Comment by ultrasaurus** [comment]
Project feature was removed in 0.10.0, so closing this
