### ISSUE TITLE
Profile usability improvement: see all opportunities at once

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#698]
We've learned that people feel proud of the work they have done and want to be able to share their accomplishments with others (currently via profile page -- also Wall of Fame is still maintained on WordPress site)

Also, people typically work on only one opportunity at a time.  Maybe they post a few, but not very many.

## Proposed UI for profile page:
Make it a list, not tabs and re-organize so the active ones are on top

### Active Opportunities
Participating
- some opportunity

Leading
- another opp
- maybe a second
- at most three

### Accomplished
Participated
- something
- something else
- more

Created
- something
- something else
- more

**Comment by ultrasaurus** [comment]
For context, it is this section of the profile page:
![image](https://cloud.githubusercontent.com/assets/41906/7049480/ba469f72-ddce-11e4-9acc-80c5319958d6.png)

**Comment by ultrasaurus** [comment]
@brandtheisey I thnk this doesn't affect you since you configure profiles to link elsewhere, right?

**Comment by brandtheisey** [comment]
We use this information, only the profile details come from an external source.

**Comment by GailSwanson** [comment]
This has been done in the new profile design
