### ISSUE TITLE
Change the people count on the Browse Project cards to show all involvement

### ISSUE THREAD

**Issue by brandtheisey** [18F/openopps-platform#790]
Currently the Browse Project card has a count of the Project Owners (which doesn't seem very useful).

I propose to change this count to include all distinct users who have commented, rsvp'd to an event, like or volunteered and portion of the project or opportunity.

So a project with 1 owners, 3 different commenters, 2 people RSVPing to events, 5 likes and 1 opportunity with 2 volunteers, 2 likes and 10 commenters would change it's people count from 1 to 24. This would hopefully increase the level of engagement and serve as a sort of "HEY SOMETHING IS GOING ON HERE" / heat meter.

The design of the card doesn't need to change, just the meaning of the one count.

**Comment by ultrasaurus** [comment]
:+1: I love this idea

**Comment by ultrasaurus** [comment]
Projects removed with 0.10.0 release, so closing this
