### ISSUE TITLE
The create Project Modal should prompt a user to add Opportunities after defining the Project

### ISSUE THREAD

**Issue by brandtheisey** [18F/openopps-platform#792]
When creating a Project, at the end of the modal, the user should be prompted to create 1 (or more) opportunities to associate with the project.

This would hopefully help define the relationship between Projects and Opportunities and help a novice user more easily understand what the system is expecting.

In the initial design, the code probably should just call the existing create Opportunity code, but there might be a chance to make Create Opportunity process better as well. Some of this possible design work has been addressed in a hackathon and documented in #318 .

**Comment by GailSwanson** [comment]
Should we close this since we don't have a project modal anymore?

**Comment by ultrasaurus** [comment]
Projects removed in 0.10.0
